server:
  port: 7777
spring:
  application:
    name: gateway-server
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"
#            allow-credentials: true
#            allowedHeaders:
#              - x-requested-with
#              - authorization
#              - content-type
#              - credential
#              - X-AUTH-TOKEN
#              - X-CSRF-TOKEN
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - PATCH
#              - DELETE
#              - OPTIONS
#            exposedHeaders:
#              - "Set-Cookie"
#              - "Authorization"
#            maxAge: 3600